name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-mongo-frontend

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Print npm and node versions
        run: |
          npm --version
          node --version

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'react-mongo-frontend/package-lock.json'

      - name: Install react-scripts
        run: npm install react-scripts@4.0.3

      - name: Install dependencies
        run: npm install --no-optional

      - name: Build
        run: npm run build --if-present
